league_to_sofascore_dict = {'ENG-Premier League': ['england', 'premier-league', '17'],
                            'ESP-La Liga': ['spain', 'laliga', '8'],
                            'FRA-Ligue 1': ['france', 'ligue-1', '34'],
                            'ITA-Serie A': ['italy', 'serie-a', '23'],
                            'GER-Bundesliga': ['germany', 'bundesliga', '35'],

                            'INT-FIFA World Cup': ['world', 'world-championship', '16'],
                            'INT-Club Friendly Games': ['world', 'club-friendly-games', '853'],
                            'INT-World Cup Qual. UEFA': ['europe', 'world-championship-qual-uefa', '11'],
                            'INT-World Cup Qual. CONCACAF': ['north-central-america', 'world-championship-qual-concacaf', '14'],
                            'INT-World Cup Qual. CONMEBOL': ['south-america', 'world-championship-qual-conmebol', '295'],
                            'INT-World Cup Qual. CAF': ['africa', 'world-championship-qual-caf', '13'],
                            'INT-World Cup Qual. AFC': ['asia', 'world-championship-qual-afc', '308'],
                            'INT-EURO': ['europe', 'european-championship', '1'],
                            'INT-International Friendly Games': ['world', 'int-friendly-games', '851'],
                            'INT-International Friendly Games Women': ['world', 'int-friendly-games-women', '852'],
                            'INT-FIFA Women\'s World Cup': ['world', 'world-championship-women', '290'],
                            'INT-Women\'s Euro': ['europe', 'womens-euro', '477'],
                            'World Championship Women Qual.': ['europe', 'world-championship-women-qual', '780'],
                            'INT-CONCACAF Gold Cup': ['north-central-america', 'concacaf-gold-cup', '140'],
                            'INT-Copa Libertadores': ['south-america', 'copa-libertadores', '16940'],

                            'EUR-UEFA Champions League': ['europe', 'uefa-champions-league', '7'],
                            'EUR-UEFA Europa League': ['europe', 'uefa-europa-league', '679'],
                            'EUR-UEFA Conference League': ['europe', 'uefa-conference-league', '17015'],
                            "EUR-UEFA Women's Champions League": ['europe', 'uefa-womens-champions-league', '696'],
                            "EUR-UEFA Women's Europa Cup": ['europe', 'uefa-womens-europa-cup', '29194'],

                            'AFG-Afghanistan Champions League': ['afghanistan', 'afghanistan-champions-league', '24194'],
                            'AFG-Shafaq Shahid Premier League': ['afghanistan', 'lig-bartar-sspl', '37664'],

                            'CAF-CAF Confederations Cup': ['africa', 'caf-confederations-cup', '1115'],
                            'Africa-CAF Champions League': ['africa', 'caf-champions-league', '1054'],
                            'Africa-CAF Confederations Cup': ['africa', 'caf-confederations-cup', '1115'],
                            'Africa-Africa Cup of Nations': ['africa', 'africa-cup-of-nations', '270'],
                            'Africa-Africa Cup of Nations Qual.': ['africa', 'africa-cup-of-nations-qual', '1848'],
                            'Africa-African Football League': ['africa', 'african-football-league', '21048'],
                            'Africa-CAF Super Cup': ['africa', 'caf-super-cup', '1250'],
                            'Africa-African Nations Championship': ['africa', 'african-nations-championship', '637'],
                            'Africa-COSAFA Cup': ['africa', 'cosafa-cup', '2076'],
                            'Africa-U23 Africa Cup of Nations': ['africa', 'u23-africa-cup-of-nations', '981'],
                            'Africa-U20 Africa Cup of Nations': ['africa', 'u20-africa-cup-of-nations', '2063'],
                            'Africa-U17 Africa Cup of Nations': ['africa', 'u17-african-cup-of-nations', '25144'],
                            'Africa-Women\'s Africa Cup of Nations': ['africa', 'africa-cup-of-nations-women', '9558'],
                            'Africa-CAF Women\'s Champions League': ['africa', 'caf-womens-champions-league', '21446'],
                            'Africa-CAF Women\'s Champions League Qualification': ['africa', 'caf-womens-champions-league-qualification', '28900'],
                            'Africa-U20 Women\'s World Cup Qualification Africa': ['africa', 'u20-womens-world-cup-qualification-africa', '34449'],
                            'Africa-UNAF U-20 Women\'s Tournament': ['africa', 'unaf-u-20-womens-tournament', '31222'],
                            'Africa-UNAF Women\'s Champions Tournament': ['africa', 'unaf-womens-champions-tournament-2026', '36771'],

                            'ALB-Abissnet Superiore': ['albania', 'abissnet-superiore', '720'],
                            'ALB-Kategoria Superiore Femra': ['albania', 'kategoria-superiore-femra', '33698'],
                            'ALB-U19 Abissnet Superiore': ['albania', 'u-19-abissnet-superiore', '35806'],

                            'AND-Primera Divisió': ['andorra', 'primera-divisio', '742'],

                            'ARG-Liga Profesional de Fútbol': ['argentina', 'liga-profesional-de-futbol', '155'],
                            'ARG-Copa de la Liga Profesional': ['argentina', 'copa-de-la-liga-profesional', '13475'],
                            'ARG-Copa Argentina': ['argentina', 'copa-argentina', '1024'],
                            'ARG-Primera Nacional': ['argentina', 'primera-nacional', '703'],
                            'ARG-Supercopa Argentina': ['argentina', 'supercopa-argentina', '1618'],
                            'ARG-Campeonato de Fútbol Femenino': ['argentina', 'primera-division-women', '10495'],
                            'ARG-Trofeo de Campeones de la Liga Profesional': ['argentina', 'trofeo-de-campeones-de-la-liga-profesional', '18436'],
                            'ARG-Campeonato de Reserva de Primera División': ['argentina', 'campeonato-de-reserva-de-primera-division', '18817'],

                            'AUT-Austrian Bundesliga': ['austria', 'bundesliga', '45'],
                            'AUT-ÖFB Cup': ['austria', 'ofb-cup', '445'],
                            'AUT-2. Liga': ['austria', '2-liga', '135'],
                            'AUT-Frauen Bundesliga': ['austria', 'frauen-bundesliga', '9415'],
                            'AUT-ÖFB Frauen Cup': ['austria', 'ofb-cup-women', '26795'],
                            'AUT-U18 ÖFB Jugendliga': ['austria', 'u18-ofb-jugendliga', '35894'],

                            'BEL-Pro League': ['belgium', 'pro-league', '38'],
                            'BEL-Challenger Pro League': ['belgium', 'challenger-pro-league', '9'],
                            'BEL-Belgian Cup': ['belgium', 'belgian-cup', '326'],
                            'BEL-Belgian Super Cup': ['belgium', 'belgian-super-cup', '338'],
                            'BEL-Belgian Women\'s Super League': ['belgium', 'belgian-womens-super-league', '2127'],
                            'BEL-Belgian Cup Women': ['belgium', 'beker-van-belgie-women', '21422'],
                            'BEL-Belgium Division 1 Women': ['belgium', 'belgium-division-1-women', '37447'],

                            'BOL-División Profesional': ['bolivia', 'division-profesional', '16736'],
                            'BOL-Copa Bolivia': ['bolivia', 'copa-division-profesional', '19891'],
                            'BOL-Copa Simón Bolívar': ['bolivia', 'copa-simon-bolivar', '19011'],
                            'BOL-Liga Nacional Sub-19': ['bolivia', 'liga-nacional-sub-19', '22711'],

                            'BRA-Brasileirão Série A': ['brazil', 'brasileirao-serie-a', '325'],
                            'BRA-Brasileirão Série B': ['brazil', 'brasileirao-serie-b', '390'],
                            'BRA-Copa do Brasil': ['brazil', 'copa-do-brasil', '329'],
                            'BRA-Supercopa do Brasil': ['brazil', 'supercopa-do-brasil', '10431'],
                            'BRA-Copa do Nordeste': ['brazil', 'copa-do-nordeste', '406'],
                            'BRA-Copa Verde': ['brazil', 'copa-verde', '427'],
                            'BRA-Copa Sul-Sudeste': ['brazil', 'copa-sul-sudeste', '33495'],
                            'BRA-U20 Campeonato Brasileiro': ['brazil', 'u20-campeonato-brasileiro', '9233'],
                            'BRA-U20 Campeonato Brasileiro Série B': ['brazil', 'u20-campeonato-brasileiro-serie-b', '25276'],

                            'BUL-Parva Liga': ['bulgaria', 'parva-liga', '247'],

                            'CAN-Canadian Premier League': ['canada', 'canadian-premier-league', '13470'],
                            'CAN-Canadian Championship': ['canada', 'canadian-championship', '9230'],
                            'CAN-Northern Super League': ['canada', 'northern-super-league', '26135'],

                            'CHI-Liga de Primera': ['chile', 'primera-division', '11653'],
                            'CHI-Liga de Ascenso': ['chile', 'primera-b', '1240'],
                            'CHI-Copa Chile': ['chile', 'copa-chile', '1221'],
                            'CHI-Segunda División': ['chile', 'segunda-division', '18834'],
                            'CHI-Supercopa de Chile': ['chile', 'supercopa-de-chile', '1309'],
                            'CHI-Chile Primera Division Women': ['chile', 'primera-division-women', '22003'],
                            'CHI-Copa de la Liga': ['chile', 'copa-de-la-liga', '32734'],
                            'CHI-U20 Campeonato Nacional Formativo': ['chile', 'campeonato-nacional-formativo-proyeccion', '22430'],
                            'CHI-U18 Campeonato Nacional Formativo': ['chile', 'campeonato-nacional-formativo-sub-18', '22431'],

                            'CRO-HNL': ['croatia', 'hnl', '170'],
                            'CRO-Croatian Cup': ['croatia', 'croatian-cup', '307'],
                            'CRO-1. NL': ['croatia', '1-nl', '724'],
                            'CRO-Croatian Super Cup': ['croatia', 'croatian-super-cup', '800'],
                            'CRO-1. HNLŽ': ['croatia', '1-hnlz', '17212'],
                            'CRO-Croatian Women\'s Football Cup': ['croatia', 'croatian-womens-football-cup', '21662'],
                            'CRO-U19 Prva NL Juniori': ['croatia', 'u19-prva-nl-juniori', '28307'],

                            'CZE-Czech First League': ['czech-republic', '1-liga', '172'],
                            'CZE-FNL': ['czech-republic', 'fnl', '205'],
                            'CZE-MOL Cup': ['czech-republic', 'czech-cup', '282'],
                            'CZE-Super Cup': ['czech-republic', 'super-cup', '798'],
                            'CZE-Czech Women\'s First League': ['czech-republic', '1-liga-women', '823'],
                            'CZE-Czech Cup Women': ['czech-republic', 'czech-cup-women', '32358'],
                            'CZE-U21': ['czech-republic', 'u21', '1303'],

                            'DEN-Danish Superliga': ['denmark', 'superliga', '39'],
                            'DEN-Betinia Liga': ['denmark', '1st-division', '47'],
                            'DEN-Oddset Pokalen': ['denmark', 'oddset-pokalen', '76'],
                            'DEN-A-Liga Women': ['denmark', 'gjensidige-kvindeliga', '9412'],
                            'DEN-B-Liga Women': ['denmark', 'b-liga-women', '28169'],
                            'DEN-Denmark U19 League': ['denmark', 'u19-ligaen', '28525'],

                            'ECU-LigaPro Serie A': ['ecuador', 'ligapro-serie-a', '240'],
                            'ECU-LigaPro Serie B': ['ecuador', 'ligapro-serie-b', '10240'],
                            'ECU-Copa Ecuador': ['ecuador', 'copa-ecuador', '13684'],
                            'ECU-Supercopa Ecuador': ['ecuador', 'super-copa', '14660'],
                            'ECU-Ecuador Superliga Femenina': ['ecuador', 'superliga-women', '26132'],

                            'EGY-Egyptian Premier League': ['egypt', 'premier-league', '808'],
                            'EGY-Egyptian Second Division A': ['egypt', 'egyptian-second-division-a', '10536'],
                            'EGY-Egypt Cup': ['egypt', 'egypt-cup', '2305'],
                            'EGY-Egyptian League Cup': ['egypt', 'egyptian-league-cup', '18491'],
                            'EGY-Egyptian Supercup': ['egypt', 'super-cup', '14688'],
                            'EGY-Premier League Women': ['egypt', 'premier-league-women', '24365'],

                            'ENG-Championship': ['england', 'championship', '18'],
                            'ENG-Community Shield': ['england', 'community-shield', '346'],
                            'ENG-League One': ['england', 'league-one', '24'],
                            'ENG-League Two': ['england', 'league-two', '25'],
                            'ENG-National League': ['england', 'national-league', '173'],
                            'ENG-FA Cup': ['england', 'fa-cup', '19'],
                            'ENG-EFL Cup': ['england', 'efl-cup', '21'],
                            'ENG-Football League Trophy': ['england', 'football-league-trophy', '334'],
                            "ENG-Women's Super League 2": ['england', 'fa-womens-championship', '10553'],
                            "ENG-Women's Super League": ['england', 'the-fa-womens-super-league', '1044'],
                            "ENG-Women's FA Cup": ['england', 'fa-cup-women', '11666'],
                            'ENG-England National League Cup': ['england', 'england-national-league-cup', '24029'],
                            "ENG-FA Women's League Cup": ['england', 'fa-womens-league-cup', '11667'],
                            'ENG-Baller League UK': ['england', 'baller-league-uk', '25492'],
                            'ENG-FA Youth Cup': ['england', 'fa-youth-cup', '24640'],

                            'FRA-Ligue 2': ['france', 'ligue-2', '182'],
                            'FRA-Ligue 3': ['france', 'national-1', '183'],
                            'FRA-National 1': ['france', 'national-2', '28153'],
                            'FRA-Coupe de France': ['france', 'coupe-de-france', '335'],
                            'FRA-Trophée des Champions': ['france', 'trophee-des-champions', '339'],
                            'FRA-Première Ligue Féminine': ['france', 'division-1-feminines', '1139'],
                            'FRA-Coupe de France Féminine': ['france', 'coupe-de-france-women', '13330'],
                            'FRA-Seconde Ligue Women': ['france', 'seconde-ligue-women', '28158'],
                            'FRA-Coupe de la Ligue Women': ['france', 'coupe-de-la-ligue-women', '30848'],
                            'FRA-Championnat National U19': ['france', 'championnat-national-u19', '11401'],

                            'GER-2. Bundesliga': ['germany', '2-bundesliga', '44'],
                            'GER-3. Liga': ['germany', '3-liga', '491'],
                            'GER-DFB Pokal': ['germany', 'dfb-pokal', '217'],
                            'GER-Franz Beckenbauer Supercup': ['germany', 'super-cup', '799'],
                            'GER-Frauen-Bundesliga': ['germany', 'frauen-bundesliga', '232'],
                            'GER-U19 DFB Nachwuchsliga': ['germany', 'a-junioren-bundesliga-playoffs', '11105'],
                            'GER-U21 Bundesliga Talent Series': ['germany', 'u21-bundesliga-talent-series', '37637'],

                            'GRE-Super League': ['greece', 'stoiximan-super-league', '185'],
                            'GRE-Super League 2': ['greece', 'super-league-2', '186'],
                            'GRE-Gamma Ethniki': ['greece', 'gamma-ethniki', '20862'],
                            'GRE-Greek Football Cup': ['greece', 'greek-cup-betsson', '375'],
                            'GRE-Greek Super Cup': ['greece', 'super-cup', '31346'],
                            'GRE-Greece Women\'s Football League': ['greece', 'super-league-women', '10609'],
                            'GRE-Greek Women\'s Cup': ['greece', 'greek-womens-cup', '31979'],
                            'GRE-U19 Super League': ['greece', 'u19-super-league', '11414'],
                            'GRE-U19 Super League 2': ['greece', 'u19-super-league-2', '24195'],

                            'IRL-Premier Division': ['ireland', 'premier-division', '192'],
                            'IRL-First Division': ['ireland', 'first-division', '193'],
                            'IRL-FAI Cup': ['ireland', 'fai-cup', '195'],
                            'IRL-Men\'s President\'s Cup': ['ireland', 'fai-presidents-cup', '1632'],
                            'IRL-Women\'s Premier Division': ['ireland', 'premier-division-women', '20065'],
                            'IRL-Women\'s FAI Cup': ['ireland', 'fai-cup-women', '22727'],
                            'IRL-Women\'s President\'s Cup': ['ireland', 'ireland-womens-super-cup', '32065'],

                            'ISR-Israeli Premier League': ['israel', 'israeli-premier-league', '266'],
                            'ISR-Israel National League': ['israel', 'national-league', '727'],
                            'ISR-Israel Super Cup': ['israel', 'israel-super-cup', '2104'],
                            'ISR-State Cup': ['israel', 'state-cup', '370'],
                            'ISR-Toto Cup Al': ['israel', 'league-cup-premier', '9355'],
                            'ISR-Toto Cup Leumit': ['israel', 'league-cup-national', '9356'],
                            'ISR-Israeli Women\'s Football League': ['israel', 'ligat-al-women', '14586'],
                            'ISR-Israel U19 Premier Division': ['israel', 'u19-premier-league', '28825'],

                            'ITA-Serie B': ['italy', 'serie-b', '53'],
                            'ITA-Coppa Italia': ['italy', 'coppa-italia', '328'],
                            'ITA-Supercoppa Italiana': ['italy', 'supercoppa-italiana', '341'],
                            'ITA-Serie C, Girone A': ['italy', 'serie-c-girone-a', '11445'],
                            'ITA-Serie C, Girone B': ['italy', 'serie-c-girone-b', '11447'],
                            'ITA-Serie C, Girone C': ['italy', 'serie-c-girone-c', '11446'],
                            'ITA-Serie C, Playoffs': ['italy', 'serie-c-playoffs', '11452'],
                            'ITA-Serie C, Play-out': ['italy', 'serie-c-play-out', '13579'],
                            'ITA-Coppa Italia Serie C': ['italy', 'coppa-italia-serie-c', '824'],
                            'ITA-Supercoppa Serie C': ['italy', 'supercoppa-serie-c', '884'],
                            'ITA-Serie A Women': ['italy', 'serie-a-femminile', '10640'],
                            "ITA-Serie A Women's Cup": ['italy', 'serie-a-cup-women', '27945'],
                            'ITA-Serie B, Women': ['italy', 'serie-b-women', '28574'],
                            'ITA-Coppa Italia Femminile': ['italy', 'coppa-italia-femminile', '13354'],
                            'ITA-Supercoppa Femminile': ['italy', 'supercoppa-femminile', '21837'],
                            'ITA-Campionato Primavera 1': ['italy', 'campionato-primavera-1', '2292'],
                            'ITA-Campionato Primavera 2': ['italy', 'campionato-primavera-2', '10534'],
                            'ITA-Primavera Cup': ['italy', 'primavera-cup', '1554'],
                            'ITA-Supercoppa Primavera': ['italy', 'supercoppa-primavera', '1910'],
                            'ITA-Serie A/B U18': ['italy', 'u18-campionato', '32180'],

                            'MEX-Liga MX, Clausura': ['mexico', 'liga-mx-clausura', '11620'],
                            'MEX-Liga MX, Apertura': ['mexico', 'liga-mx-apertura', '11621'],
                            'MEX-Liga de Expansión MX': ['mexico', 'liga-de-expansion-mx', '697'],
                            'MEX-Copa MX': ['mexico', 'copa-mx', '1598'],
                            'MEX-Supercopa MX': ['mexico', 'supercopa-mx', '1754'],
                            'MEX-Liga MX Women': ['mexico', 'liga-mx-women', '10770'],
                            'MEX-U23 Liga MX Apertura': ['mexico', 'u23-liga-mx-apertura', '20710'],

                            'NED-Eredivisie': ['netherlands', 'eredivisie', '37'],
                            'NED-Eerste Divisie': ['netherlands', 'eerste-divisie', '131'],
                            'NED-Tweede Divisie': ['netherlands', 'tweede-divisie', '11402'],
                            'NED-KNVB Beker': ['netherlands', 'knvb-beker', '330'],
                            'NED-Johan Cruijff Schaal': ['netherlands', 'johan-cruijff-schaal', '340'],
                            'NED-Women\'s Eredivisie': ['netherlands', 'vrouwen-eredivisie', '2123'],
                            'NED-KNVB Beker Women': ['netherlands', 'knvb-beker-women', '18789'],
                            'NED-U21 KNVB Divisie 1': ['netherlands', 'u21-knvb-divisie-1', '17143'],
                            'NED-U19 Eredivisie': ['netherlands', 'u19-eredivisie', '29890'],

                            'NOR-Eliteserien': ['norway', 'eliteserien', '20'],
                            'NOR-1. Division': ['norway', '1st-division', '21'],
                            'NOR-2. Division': ['norway', '2nd-division', '22'],
                            'NOR-NM Cup': ['norway', 'nm-cup', '19'],
                            'NOR-Toppserien': ['norway', 'toppserien-women', '201'],
                            'NOR-1. Division Women': ['norway', '1st-division-women', '154'],
                            'NOR-Nasjonal U19 CL': ['norway', 'nasjonal-u19-cl', '21931'],

                            'PAR-Primera División Apertura': ['paraguay', 'primera-division-apertura', '11540'],
                            'PAR-Primera División Clausura': ['paraguay', 'primera-division-clausura', '11541'],
                            'PAR-División Intermedia': ['paraguay', 'division-intermedia', '1254'],
                            'PAR-Copa Paraguay': ['paraguay', 'copa-paraguay', '11542'],
                            'PAR-Supercopa Paraguay': ['paraguay', 'supercopa-paraguay', '11543'],
                            'PAR-Campeonato Femenino': ['paraguay', 'campeonato-femenino', '426'],

                            'PER-Liga 1': ['peru', 'liga-1', '406'],
                            'PER-Liga 2': ['peru', 'liga-2', '10297'],
                            'PER-Liga 3': ['peru', 'liga-3', '29030'],
                            'PER-Copa Perú': ['peru', 'copa-peru', '21191'],
                            'PER-Supercopa Peruana': ['peru', 'supercopa-peruana', '14603'],

                            'POL-Ekstraklasa': ['poland', 'ekstraklasa', '202'],
                            'POL-1. Liga': ['poland', 'i-liga', '229'],
                            'POL-2. Liga': ['poland', 'ii-liga', '515'],
                            'POL-Polish Cup': ['poland', 'puchar-polski', '281'],
                            'POL-Polish Super Cup': ['poland', 'superpuchar-polski', '511'],
                            'POL-Women\'s Ekstraliga': ['poland', 'ekstraliga-women', '10499'],
                            'POL-Women\'s 1. Liga': ['poland', 'orlen-i-liga-kobiet', '23249'],
                            'POL-Polish Women\'s Cup': ['poland', 'puchar-polski-women', '37295'],
                            'POL-U19 CLJ': ['poland', 'u19-clj', '1365'],

                            'POR-Liga Portugal': ['portugal', 'liga-portugal-betclic', '238'],
                            'POR-Liga Portugal 2': ['portugal', 'liga-portugal-2', '239'],
                            'POR-Liga 3': ['portugal', 'liga-3', '17101'],
                            'POR-Campeonato de Portugal': ['portugal', 'campeonato-de-portugal', '10093'],
                            'POR-Taça de Portugal': ['portugal', 'taca-de-portugal', '336'],
                            'POR-Taça da Liga': ['portugal', 'taca-da-liga', '327'],
                            'POR-Supertaça': ['portugal', 'supertaca', '345'],
                            'POR-Campeonato Nacional Feminino': ['portugal', 'campeonato-nacional-feminino', '224'],
                            'POR-Taça de Portugal Feminina': ['portugal', 'taca-de-portugal-feminina', '24151'],
                            'POR-Supertaca Women': ['portugal', 'supertaca-women', '24016'],
                            'POR-Taça da Liga Feminina': ['portugal', 'taca-da-liga-feminina', '24017'],
                            'POR-U23 Liga Next Gen': ['portugal', 'u23-liga-revelacao', '11341'],
                            'POR-U23 Taça Revelação': ['portugal', 'u23-taca-revelacao', '13543'],
                            'POR-U19 Championship': ['portugal', 'u19-championship', '1133'],
                            'POR-U19 Championship II Division': ['portugal', 'u19-campeonato-nacional-ii-divisao', '23150'],

                            'ROU-SuperLiga': ['romania', 'superliga', '152'],
                            'ROU-Liga II': ['romania', 'liga-ii', '203'],
                            'ROU-Liga III': ['romania', 'liga-iii', '204'],
                            'ROU-Cupa României': ['romania', 'cupa-romaniei', '355'],
                            'ROU-Supercupa României': ['romania', 'supercupa-romaniei', '698'],
                            'ROU-SuperLiga Women': ['romania', 'superliga-women', '1318'],
                            'ROU-Cupa României Women': ['romania', 'cupa-romaniei-women', '13719'],
                            'ROU-Campionatul Național U19': ['romania', 'campionatul-national-u19', '24254'],

                            'RUS-Russian Premier League': ['russia', 'premier-league', '203'],
                            'RUS-First League': ['russia', '1-liga', '204'],
                            'RUS-Second League Division A': ['russia', 'second-league-division-a', '1427'],
                            'RUS-Russian Cup': ['russia', 'russian-cup', '21'],
                            'RUS-Russian Super Cup': ['russia', 'russian-supercup', '397'],
                            'RUS-Super League Women': ['russia', 'super-league-women', '165'],
                            'RUS-Russian Women\'s Cup': ['russia', 'russian-womens-cup', '1650'],

                            'KSA-Saudi Pro League': ['saudi-arabia', 'saudi-pro-league', '955'],
                            'KSA-Saudi First Division': ['saudi-arabia', 'first-division', '958'],
                            'KSA-King\'s Cup': ['saudi-arabia', 'kings-cup', '2058'],
                            'KSA-Saudi Super Cup': ['saudi-arabia', 'saudi-super-cup', '2119'],
                            'KSA-Saudi Women\'s Premier League': ['saudi-arabia', 'saudi-womens-premier-league', '23064'],
                            'KSA-U19 Saudi Elite Development League': ['saudi-arabia', 'u19-saudi-elite-development-league', '35144'],

                            'SRB-Serbian SuperLiga': ['serbia', 'superliga', '210'],
                            'SRB-Serbian First League': ['serbia', 'prva-liga', '211'],
                            'SRB-Serbian Cup': ['serbia', 'serbian-cup', '212'],
                            'SRB-Serbian Super Cup': ['serbia', 'serbian-super-cup', '213'],
                            'SRB-Serbian Women\'s Super League': ['serbia', 'serbian-womens-super-league', '23441'],
                            'SRB-U19 League': ['serbia', 'u19-league', '28710'],

                            'SVK-Niké Liga': ['slovakia', 'nike-liga', '192'],
                            'SVK-2. Liga': ['slovakia', '2-liga', '193'],
                            'SVK-Slovak Cup': ['slovakia', 'slovak-cup', '213'],
                            'SVK-Slovak Super Cup': ['slovakia', 'slovak-super-cup', '214'],
                            'SVK-Niké Liga Women': ['slovakia', 'nike-liga-women', '23442'],
                            'SVK-U19 Slovakia League': ['slovakia', 'u19-1-liga', '1327'],

                            'ESP-Segunda División': ['spain', 'segunda-division', '54'],
                            'ESP-Primera Federación': ['spain', 'primera-federacion', '17073'],
                            'ESP-Segunda Federación': ['spain', 'segunda-federacion', '544'],
                            'ESP-Copa del Rey': ['spain', 'copa-del-rey', '329'],
                            'ESP-Supercopa de España': ['spain', 'supercopa-de-espana', '494'],
                            'ESP-Copa Federación': ['spain', 'copa-federacion', '17074'],
                            'ESP-Liga F': ['spain', 'liga-f', '1127'],
                            'ESP-Copa de SM La Reina': ['spain', 'copa-de-sm-la-reina', '11126'],
                            'ESP-Supercopa Femenina': ['spain', 'supercopa-femenina', '14687'],
                            'ESP-División de Honor Juvenil': ['spain', 'u19-division-de-honor-juvenil', '28749'],

                            'RSA-Premiership': ['south-africa', 'premiership', '325'],
                            'RSA-National First Division': ['south-africa', 'national-first-division', '326'],
                            'RSA-Nedbank Cup': ['south-africa', 'nedbank-cup', '327'],
                            'RSA-MTN 8': ['south-africa', 'mtn-8', '329'],
                            'RSA-South African Women\'s Super League': ['south-africa', 'hollywoodbets-super-league', '23063'],

                            'SWE-Allsvenskan': ['sweden', 'allsvenskan', '40'],
                            'SWE-Superettan': ['sweden', 'superettan', '46'],
                            'SWE-Ettan': ['sweden', 'ettan', '44'],
                            'SWE-Svenska Cupen': ['sweden', 'svenska-cupen', '48'],
                            'SWE-Damallsvenskan': ['sweden', 'damallsvenskan', '214'],
                            'SWE-Elitettan': ['sweden', 'elitettan', '215'],
                            'SWE-Svenska Cupen Women': ['sweden', 'svenska-cupen-women', '217'],
                            'SWE-U19 Allsvenskan': ['sweden', 'u19-allsvenskan', '3090'],

                            'SUI-Swiss Super League': ['switzerland', 'super-league', '215'],
                            'SUI-Challenge League': ['switzerland', 'challenge-league', '216'],
                            'SUI-Swiss Cup': ['switzerland', 'swiss-cup', '217'],
                            'SUI-Swiss Promotion League': ['switzerland', 'promotion-league', '218'],
                            'SUI-Swiss Women\'s Super League': ['switzerland', 'super-league-women', '219'],
                            'SUI-Swiss Women\'s Cup': ['switzerland', 'schweizer-cup-women', '220'],
                            'SUI-Switzerland U19 Elite League': ['switzerland', 'u19-elite', '28711'],

                            'THA-Thai League 1': ['thailand', 'thai-league-1', '1032'],
                            'THA-Thai League 2': ['thailand', 'thai-league-2', '10511'],
                            'THA-Thai FA Cup': ['thailand', 'fa-cup', '21779'],
                            'THA-Thai Women\'s League 1': ['thailand', 'thai-womens-league-1', '23120'],
                            'THA-Thailand League Cup': ['thailand', 'thailand-league-cup', '23798'],

                            'TUR-Trendyol Süper Lig': ['turkey', 'trendyol-super-lig', '52'],
                            'TUR-Trendyol 1. Lig': ['turkey', 'trendyol-1lig', '98'],
                            'TUR-Nesine 2. Lig': ['turkey', 'tff-2-lig', '97'],
                            'TUR-Türkiye Kupası': ['turkey', 'turkiye-kupasi', '96'],
                            'TUR-TFF Süper Kupa': ['turkey', 'tff-super-kupa', '505'],
                            'TUR-Turkish Women\'s Super League': ['turkey', 'turkish-womens-super-league', '23427'],
                            'TUR-Kadınlar 1. Ligi': ['turkey', '1-liga-women', '24295'],
                            'TUR-U19 Elit A Ligi': ['turkey', 'u19-lig-elit-a-grup-1', '13959'],
                            'TUR-U19 Elit B Ligi': ['turkey', 'u19-lig-elit-b', '13960'],

                            'USA-MLS': ['usa', 'mls', '242'],
                            'USA-USL Championship': ['usa', 'usl-championship', '13363'],
                            'USA-USL League One': ['usa', 'usl-league-one', '13362'],
                            'USA-MLS Next Pro': ['usa', 'mls-next-pro', '18641'],
                            'USA-US Open Cup': ['usa', 'us-open-cup', '495'],
                            'USA-National Women\'s Soccer League': ['usa', 'nwsl', '1690'],
                            'USA-USL Super League': ['usa', 'usl-super-league-women', '28384'],
                            'USA-NWSL Challenge Cup': ['usa', 'nwsl-challenge-cup', '14820'],
                            }

